### ISSUE TITLE
Rome's Roadmap

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/rome#1]
This issue contains details for Rome's roadmap/feature lookahead, to be continuously updated.

## Core

- [ ] `rome`: Tagged template function that takes Rome and returns a string of HTML, embeds components through template literals.
  ```ts
  const App: string = () => rome`<div>${Button("Click me!")}</div>`;
  const Button: string = (text: string) => rome`<button class="primary">${text}</button>`;
  ```
- [ ] `state`: Initializes reactive state, provides setter/getter.
  ```ts
  function App() {
    const mode = state("dark");

    return rome`
      <div class="${mode}">
        ...
      </div>
    `
  }
  ```
- [ ] `when`: Runs a function when given event occurs.
  ```ts
  function App() {
    const mode = state("dark");

    return rome`
      <div class="${mode}">
        <button whenClick="${mode.set("light")}">Light</button>
      </div>
    `
  }
  ```
